import { Inter } from "next/font/google";
import HeaderNav from "@/components/header/headerNav";
import Footer from "@/components/slideshow/footer/footer";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="container">
          <HeaderNav/> 
          <main className="main">
            {children}
          </main>
          <Footer/>
        </div>
      </body>
    </html>
  );
}
